### ISSUE TITLE
Clarification on time:beat

### ISSUE THREAD

**Issue by milasudril** [drobilla/lv2#11]
> Property time:beat
beat
OWL Type	Datatype Property
Domain	time:Time
Range	xsd:double

What is the intention about time:beat? Is it a global counter, or is it the same as time:barBeat, with double precision?  The question rose because Qtractor delivered me the barBeat value, but as a long, and I thought it was intended as a global value.

**Comment by drobilla** [comment]
Hm.  I intended it as a global running time in beats, but the spec is ambiguous about this.  This might need discussing on the mailing list.

However, it is explicitly specified as double, so sending a long isn't right.

**Comment by drobilla** [comment]
Fixed in 6803758, thanks.
