### ISSUE TITLE
Building your own  lv2 

### ISSUE THREAD

**Issue by Reaper10** [drobilla/lv2#13]
Could someone Build a software for Building your own  lv2 something like ,
SynthEdit
http://www.synthedit.com/

or

FLowstone 
http://www.image-line.com/plugins/Tools/FlowStone/

basically could someone make a IDE software for making lv2s

**Comment by drobilla** [comment]
Please don't open issues for LV2 itself with general wishes for LV2-related software.  The [mailing list](http://lists.lv2plug.in/listinfo.cgi/devel-lv2plug.in) is the best place for general discussion.

That said, http://drobilla.net/software/ingen
