### ISSUE TITLE
MIDI gate is not very happy in Ardour

### ISSUE THREAD

**Issue by io7m** [drobilla/lv2#18]
Hello!

The behaviour of the MIDI Gate plugin seems somewhat erratic when used inside Ardour. For whatever reason, it seems that almost immediately the plugin gets out of sync with regards to whether or not there are MIDI notes playing. Often, the gate will get stuck either off or on. Sometimes it'll even give different results for the left and right audio channel (stuck on left, stuck off right, etc).

This is the latest source (from this repos) and Ardour 5.12 built from Arch Linux packages.

I realize the above is not much to go on. If there's more information I can give you, let me know!

**Comment by io7m** [comment]
It's just been pointed out to me that the plugin is 1 in / 1 out, so Ardour is cloning the plugin at the very least. That would at least explain why there's the left/right imbalance (both plugin instances are behaving erratically in different ways).

**Comment by io7m** [comment]
Current theory is that Ardour may be sending unexpected program changes. I'm still investigating. It may also be down to one or more plugins that are placed in front of the gate and that don't pass on midi events properly. Having had the above bug me for about six months, I'm now unable to reproduce it with just a synth and the gate plugin on its own.

**Comment by io7m** [comment]
OK, on the advice of @x42 I added the MIDI monitor plugin before the gate effect, and it seems like what can happen is that if you stop playback of the track in the middle of a note, then the note-off event for the note may not make it to the plugin. In effect, the plugin thinks there's a note playing that's never released. It's not clear to me what the right way to fix this would be...

**Comment by x42** [comment]
The plugin should respond to the "all note off" (midi panic) message.

**Comment by io7m** [comment]
Is this `wontfix`?

**Comment by drobilla** [comment]
Sorry, I mistook this as being about something else.

**Comment by drobilla** [comment]
Fixed in 728196c9d55100b63b74b2f118bd80d451636a6c

**Comment by io7m** [comment]
Thanks!
