### ISSUE TITLE
Request: lv2:shortname

### ISSUE THREAD

**Issue by falkTX** [drobilla/lv2#2]
Right now in LV2 we have full-length parameter names and identifier symbols.
Using the full name of a parameter is not always a good idea though, specially for hosts that don't reserve a lot of space for them.

I propose adding an official lv2:shortname, ala doap:shortname but that can be used for lv2 stuff like parameters.
We need it in MOD because some plugins (like setbfree FXs) have seriously long names.
It's possible to automatically crop the name, but the result is not always understandable.
DAWs with a direct-parameter-access in the mixer strip (like Ardour and Qtractor) can benefit from this as well.

**Comment by falkTX** [comment]
btw, I'm not proposing that all plugins will need to add this property, it should be optional.
Hosts can look for this shortname first and use the full one as fallback.

**Comment by drobilla** [comment]
A patch/pull request that adds said property would have been less typing than that comment ;)

**Comment by falkTX** [comment]
I did a quick patch for it already, but the comment on it is terrible...

```
From cc48b1f968ce2d07d1e50a3d7fb28ad0df11edad Mon Sep 17 00:00:00 2001
From: falkTX <falktx@gmail.com>
Date: Wed, 1 Jul 2015 15:45:43 +0200
Subject: [PATCH] Add lv2:shortname property

---
 lv2/lv2plug.in/ns/lv2core/lv2core.ttl | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git a/lv2/lv2plug.in/ns/lv2core/lv2core.ttl b/lv2/lv2plug.in/ns/lv2core/lv2core.ttl
index 723f6dc..4261c82 100644
--- a/lv2/lv2plug.in/ns/lv2core/lv2core.ttl
+++ b/lv2/lv2plug.in/ns/lv2core/lv2core.ttl
@@ -474,6 +474,15 @@ lv2:name
 
 This property is required for Ports, but MUST NOT be used by the host for port identification. The plugin author may change the values of this property without changing the Plugin URI.""" .
 
+lv2:shortname
+	a rdf:Property ,
+		owl:DatatypeProperty ;
+	rdfs:label "short name" ;
+	rdfs:range xsd:string ;
+	rdfs:comment """A short display name for labeling in a user interface.
+
+The same rules for port names apply here, with the exception that short names should not be longer than 16 characters.""" .
+
 lv2:Designation
 	a rdfs:Class ,
 		owl:Class ;
```

**Comment by drobilla** [comment]
Thanks.  Added in a34ea33 but as lv2:shortName (LV2 consistently uses camelCase, doap is a bit sloppy in this regard)
