### ISSUE TITLE
 lv2 compiler commands for window

### ISSUE THREAD

**Issue by Reaper10** [drobilla/lv2#20]
Could one make a lv2 compiler commands for building lv2 plugins on window? Being that more and more daws are on windows are stating to use lv2 plugins. This will those on those on the motioned os who want your plugins but aren't coders.
could ms power shell used for this?

**Comment by drd-ableton** [comment]
Yes, LV2 can be used on Windows.  People have built them with gcc, clang, and msvc.  Powershell is not a compiler, but you can build on the command line if you like.  There is nothing particularly special about LV2 here, it's just like building any other dynamically loadable module.

**Comment by drobilla** [comment]
Yes, LV2 can be used on Windows. People have built them with gcc, clang, and msvc. Powershell is not a compiler, but you can build on the command line if you like. There is nothing particularly special about LV2 here, it's just like building any other dynamically loadable module.
