### ISSUE TITLE
LV2 URI/URLs don't resolve via HTTPs anymore

### ISSUE THREAD

**Issue by x42** [drobilla/lv2#30]
All LV2 prefix URI/URLs are 404 Not Found.

Visit  http://lv2plug.in/ns/lv2core/lv2core.html  that describes `http://lv2plug.in/ns/lv2core#`
At the top of the page, there is even a lnk to http://lv2plug.in/ns/lv2core -- that is currently 404

**Comment by drobilla** [comment]
Actually it's just the core (because it's a special case with the weird naming).

**Comment by drobilla** [comment]
Fixed in 95bc2dde1a7634844ccc3c41382f365d9c721efc, thanks.

**Comment by drobilla** [comment]
(I updated the online docs right away since nothing significant has changed since 1.16.0)

**Comment by x42** [comment]
Thanks! Works now again just fine,
