### ISSUE TITLE
LV2 atoms are not portable between architectures with different endianess

### ISSUE THREAD

**Issue by sadko4u** [drobilla/lv2#36]
From LV2 spec:

```
Each Atom type defines a binary format for use at runtime, but also a serialisation that is natural
to express in Turtle format. Thus, this specification defines a powerful real-time appropriate
data model, as well as a *portable* way to serialise any data in that model. This is particularly
useful for inter-process communication, saving/restoring state, and describing values in plugin data files.
```
If we try to send an atom POD from LE architecture to the BE architecture, we'll get nothing good. OSC protocol solves this issues by just specifying that all data *should* be stored in big-endian format. LV2's forge and parse headers don't take any considerations about endianess of the architecture when encoding/decoding PODs.

**Comment by ventosus** [comment]
> If we try to send an atom POD from LE architecture to the BE architecture, we'll get nothing good. 

Well, you cannot share POD between machines without doing some serialization.

Atoms are meant to be shared between host/plugin and/or plugin/plugin. Host and plugins will run on the same machine in 99.999% of cases.

In the 0.001% of cases where you want atoms to cross machines, just put in a serialization step (that's the host's job). It makes no sense to route Atoms in an endianness-agnostic way on the very same machine. There's just too much overhead without any gain at all.

> OSC protocol solves this issues by just specifying that all data should be stored in big-endian
> format.

OSC is predominantly transfered via UDP/TCP. As it is involved in networking, it needs to handle endianness, of course. Again: Atoms are transferred between host/plugin or plugin/plugin. There's no change in endianness expected there.

> LV2's forge and parse headers don't take any considerations about endianess of the 
> architecture when encoding/decoding PODs.

If you have to cross an endianness barrier, use a serializer like sratom [1] which serializes to turtle.

In synthpod [2] I use a binary serializer [3] with optional endianness switch.

[1] http://drobilla.net/software/sratom
[2] https://git.open-music-kontrollers.ch/lv2/synthpod/
[3] https://git.open-music-kontrollers.ch/lv2/netatom.lv2/

**Comment by drobilla** [comment]
Indeed, this is intentional.  The OSC approach would be a mistake in plugins, because then you would have to do a bunch of endian nonsense in realtime (we would also remove that rule if there's ever an LV2 OSC extension for the same reason).
