### ISSUE TITLE
LV2_State_Interface does not provide functions to iterate all saved states.

### ISSUE THREAD

**Issue by sadko4u** [drobilla/lv2#37]
Consider a plugin that can save different number of various parameters. When it saves the state, it exactly knows the set of stored parameters. But how it should handle all parameters when the state is restored? Current function prototype:
```
	LV2_State_Status (*restore)(LV2_Handle                  instance,
	                            LV2_State_Retrieve_Function retrieve,
	                            LV2_State_Handle            handle,
	                            uint32_t                    flags,
	                            const LV2_Feature *const *  features);
```
does only allow to retrieve the property with URID that plugin exactly knows. But what if plugin does generate URID, for example, according to the following schema:
```
http://lsp-plug.in/kvt/scene/object/<object-id>/material/dissipation/inner
```
?
Even if we know the number of objects, there is no possibility to write generalized code that provides a key-value storage that will be saved with the LV2:State interface and then fully restored.

It would be nice to have some **Iterator** interface that could allow the plugin to iterate all properties previously stored in it's state and handle them manually.

**Comment by drobilla** [comment]
This is deliberate, and the only way the state interface could be so simple.  Store a property with an object value if you want to store a bunch of variable properties and be able to iterate over them (or whatever) on restore.
