### ISSUE TITLE
UI resize should also be an extensionData

### ISSUE THREAD

**Issue by falkTX** [drobilla/lv2#4]
Some plugins are exposing resize to the host via extensionData (infamous-plugins).
This allows the host to resize the plugin UI without caring much about the underlying system.

As per good lv2 practice we declare the support extension-data in the ttl file, like this:
```
lv2:extensionData ui:idleInterface, ui:resize ;
```

ui:resize is not an extensionData though, and sord_validate complains.

**Comment by drobilla** [comment]
Fixed in 44d37a772b2f85e1a05a05d042bc4467b5db6724
